server:
  port: 8000
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
    # hikariCp property setting
    pool-name: HikariCP
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    auto-commit: true
    connection-init-sql: SELECT 1
  security:
    user:
      name: admin
      password: admin
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    open-in-view: false
  jackson:
    time-zone: Asia/Seoul


jwt:
  token:
    secret-key: 
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000
  redis:
    host: redis
    port: 6379
    password: 


# Multipart File Upload Setting
file:
  multipart:
    maxUploadSize: 1000000
    maxUploadSizePerFile: 1000000


# Swagger setting
springdoc:
  packages-to-scan: com.rezero.rotto.api.controller
  swagger-ui:
    path: /api-docs
    groups-order: DESC
    tags:sorter: alpha
    operations-sorter: alpha
    disabled-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  show-actuator: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


  # log level Setting
  logging:
    level:
      root: info
      org:
        springframework:
          root: debug
          web: debug
      com:
        rotto: debug
      zaxxer:
        hikari:
          pool:
            HikariPool: debug


# S3 Bucket
cloud:
  aws:
    s3:
      # 수정 필요
      bucket: 
    region:
      static: 
    credentials:
      access-key: 
      secret-key: 
    stack:
      auto: false

